In [ ]:
print("hello, world")
print("Welcome")

hello, world
Welcome

In [ ]:
if 5 > 2:
  print("Five is greater than two!")
if 7<13:
  print("7 is less than 13!")
if 17<23:
      print("17 is less than 23!")

Five is greater than two!
7 is less than 13!
17 is less than 23!

In [ ]:
x=10
y="hello"
print(x)
print(y)

10
hello

In [ ]:
x=20
y=30
print(x+y)

50

In [ ]:
x="ab"
y="cd"
print(x+y)

abcd

In [ ]:
#case sensitiveness of variable
a = 4
A = "Sally"
print(A)
print(a)

Sally
4

In [ ]:
#variable single quote, double quote
x = "John"
print(x)
x = 'John'
print(x)

John
John

In [ ]:
#casting of variable
x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3) 
print(x)
print(y)
print(z)

3
3
3.0

In [ ]:

#identify data type of variable
x = 5
y = "John"
z=3.4
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'str'>
<class 'float'>

In [ ]:
#different ways to represent variables
myvar = "John"
my_var = "John"
_my_var = "John"
myVar = "John"
MYVAR = "John"
myvar2 = "John"
print(myvar)
print(my_var)
print(_my_var)
print(myVar)
print(MYVAR)
print(myvar2)

John
John
John
John
John
John

In [ ]:
#multiword variable names
myVariableName = "John"  #camel case
MyVariableName = "John"#pascle case
my_variable_name = "John"#snake case
print(myVariableName)
print(MyVariableName)
print(my_variable_name)

John
John
John

In [ ]:
#assign multiple values to varible
x, y, z,q = "Orange", "Banana", "Cherry", 10
print(x)
print(y)
print(z)
print(q)

Orange
Banana
Cherry
10

In [ ]:
#one value to multiple variables
x = y = z = "Orange"
print(x)
print(y)
print(z)

Orange
Orange
Orange

In [ ]:
#unpack a collection, list into variable
fruits = {"apple", "banana", "cherry"}
veg=["potato","bringle","tomato"]
x, y, z = fruits
p,q,r=veg
print(x,y,z)
print(p,q,r)

banana apple cherry
potato bringle tomato

In [ ]:
x = "Python\n"
y = "is\n"
z = "awesome\n"
print(x, y, z)
print(x + y + z)

Python
 is
 awesome

Python
is
awesome

In [ ]:
x = 5
y = "John"
print(x, y)

5 John

In [ ]:
#global variable
x = "awesome"

def myfunc():
  print("Python is " + x)

myfunc()

Python is awesome

In [ ]:
#global variable
x = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()

print("Python is " + x)

Python is fantastic
Python is awesome

In [ ]:
#get data type
x = "Hello World"	#str	
print(type(x))
x = 20	#int	
print(type(x))
x = 20.5	#float	
print(type(x))
x = 1j	#complex	
print(type(x))
x = ["apple", "banana", "cherry"]	#list	
print(type(x))
x = ("apple", "banana", "cherry")	#tuple	
print(type(x))
x = range(6)	#range	
print(type(x))
x = {"name" : "John", "age" : 36}	#dict	
print(type(x))
x = {"apple", "banana", "cherry"}	#set	
print(type(x))
x = frozenset({"apple", "banana", "cherry"})	#frozenset	
print(type(x))
x = True	#bool	
print(type(x))
x = b"Hello"	#bytes	
print(type(x))
x = bytearray(5)	#bytearray
print(type(x))	
x = memoryview(bytes(5))	#memoryview	
print(type(x))
x = None
print(type(x))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'complex'>
<class 'list'>
<class 'tuple'>
<class 'range'>
<class 'dict'>
<class 'set'>
<class 'frozenset'>
<class 'bool'>
<class 'bytes'>
<class 'bytearray'>
<class 'memoryview'>
<class 'NoneType'>

In [ ]:
#using data types
x = str("Hello World")	#str
print(x)	
x = int(20)	#int	
print(x)
x = float(20.5)	#float	
print(x)
x = complex(1j)	#complex	
print(x)
x = list(("apple", "banana", "cherry"))	#list	
print(x)
x = tuple(("apple", "banana", "cherry"))	#tuple	
print(x)
x = range(10)	#range	
print(x)
x = dict(name="John", age=36)	#dict	
print(x)
x = set(("apple", "banana", "cherry"))	#set	
print(x)
x = frozenset(("apple", "banana", "cherry"))	#frozenset	
print(x)
x = bool(5)	#bool	
print(x)
x = bytes(5)	#bytes	
print(x)
x = bytearray(5)	#bytearray	
print(x)
x = memoryview(bytes(5))
print(x)

Hello World
20
20.5
1j
['apple', 'banana', 'cherry']
('apple', 'banana', 'cherry')
range(0, 10)
{'name': 'John', 'age': 36}
{'banana', 'apple', 'cherry'}
frozenset({'banana', 'apple', 'cherry'})
True
b'\x00\x00\x00\x00\x00'
bytearray(b'\x00\x00\x00\x00\x00')
<memory at 0x7f1ebbfb2a10>

In [ ]:
#using numbers
x = 35e3
y = 12E4
z = -87.7e100

print(type(x))
print(type(y))
print(type(z))

x = 1
y = 35656222554887711
z = -3255522
print(type(x))
print(type(y))
print(type(z))

x = 1    # int
y = 2.8  # float
z = 1j   # complex
print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'float'>
<class 'complex'>

In [ ]:
#multiline string
a = """Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."""
print(a)

Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.

In [ ]:
#string as array
a = "Hello, World!"
print(a[1])
print(a[4])
print(a[7])

e
o
W

In [ ]:
#looping through string
for x in "banana":
  print(x)
for y in "Hello":
  print(y)

b
a
n
a
n
a
H
e
l
l
o

In [ ]:
#get string length
x="Hello"
y="Good morning"
print(len(x))
print(len(y))

5
12

In [ ]:
#to check whether substring is present or not
txt = "The best things in life are free!"
print("free" in txt)
print("java"in txt)

True
False

In [ ]:
#to check whether substring is present or not using if 
txt = "The best things in life are free!"
if "free" in txt:
  print("Yes, 'free' is present.")


if "java" not in txt:
  print("No, 'Java' is not present.")

Yes, 'free' is present.
No, 'Java' is not present.

In [ ]:
#slicing, range of characters
b = "Hello, World!"
print(b[:5])     #from start

print(b[2:5])  # range

print(b[3:])  #to the end

print(b[-5:-3]) #negative indexing
print(b[-5:-2])

Hello
llo
lo, World!
or
orl

In [ ]:
#string functions
a = "Hello, World!"
print(a.upper())    #uppercase

print(a.lower())     #lowercase

print(a.strip())   #removes white space

print(a.replace("H", "J")) #replace string

print(a.split(",")) # returns ['Hello', ' World!']    #split string

#concatenation
a = "Hello"
b = "World"
c = a + b
print(c)

c = a + " " + b
print(c)

HELLO, WORLD!
hello, world!
Hello, World!
Jello, World!
['Hello', ' World!']
HelloWorld
Hello World

In [ ]:
#use of format to combine string and numbers
age = 36
txt = "My name is John, and I am {}"
print(txt.format(age))

quantity = 3
itemno = 567
price = 49.95
myorder = "I want {} pieces of item {} for {} dollars."
print(myorder.format(quantity, itemno, price))

My name is John, and I am 36
I want 3 pieces of item 567 for 49.95 dollars.

In [ ]:
#escape char for double quote inside double quote
txt = "We are the so-called \"Vikings\" from the north."
print(txt)

We are the so-called "Vikings" from the north.

In [ ]:
#string functions
txt = "hello, and welcome to my world."
x = txt.capitalize()#uppercase first letter
print (x)

txt = "Hello, And Welcome To My World!"
x = txt.casefold()#lowercase first letter
print(x)

txt = "banana"
x = txt.center(20)#taking up the space of 20 characters, with "banana" in the middle:
print(x)

x = txt.center(20, "O")#Using the letter "O" as the padding character
print(x)

txt = "I love apples, apple are my favorite fruit"
x = txt.count("apple") #Return the number of times the value "apple" appears in the string:
print(x)

x = txt.count("apple", 10, 24) #Search from position 10 to 24:
print(x)

txt = "Hello, welcome to my world."
x = txt.endswith(".")#Check if the string ends with a punctuation sign
print(x)

x = txt.endswith("my world.")#Check if the string ends with the phrase "my world.":
print(x)

x = txt.endswith("my world.", 5, 11)
print(x)

x = txt.endswith("my world.", 5, 11)#Check if position 5 to 11 ends with the phrase "my world.":
print(x)

x = txt.startswith("Hello")#Check if the string starts with "Hello":
print(x)

x = txt.startswith("wel", 7, 20)#Check if position 7 to 20 starts with the characters "wel":
print(x)

Hello, and welcome to my world.
hello, and welcome to my world!
       banana
OOOOOOObananaOOOOOOO
2
1
True
True
False
False
True
True

In [ ]:
# boolean values
print(10 > 9)
print(10 == 9)
print(10 < 9)


a = 200
b = 33

if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")

  x = "Hello"
y = 15

print(bool(x))
print(bool(y))

True
False
False
b is not greater than a
True
True

In [ ]:
# Python Arithmetic Operators
x = 5
y = 3

print(x + y)#addition
print(x - y)#substraction
print(x * y)#multiplication
print(x/y)#division
print(x%y)#modulus
print(x**y) # exponent
print(x//y) #floor division
print(x)#assignment

#Python Assignment Operators
x = 5
x += 3
print(x)#+= operator

x = 5
x -= 3
print(x)#-= operator

x *= 3
print(x)#*= operator

x /= 3
print(x)#/= operator

x = 5
x %= 3
print(x)#%= operator

x = 5
x //= 3
print(x)#//= operator

x = 5
x **= 3
print(x)#**= operator

x &= 3
print(x)#&= operator

x |= 3
print(x)#|= operator

x ^= 3
print(x)#^= operator

x >>= 3
print(x)#>>= operator

x <<= 3
print(x)#<<= operator

#Python Comparison Operators
x = 5
y = 3
print(x == y)
print(x != y)
print(x > y)
print(x < y)
print(x >= y)
print(x <= y)

#Python Logical Operators
x = 5
print(x > 3 and x < 10)    #logical and operator
print(x > 3 or x < 4)   #logical or operator
print(not(x > 3 and x < 10))     #logical not operator

#Python Identity Operators
x = ["apple", "banana"]
y = ["apple", "banana"]
z = x
print(x is z)   # returns True because z is the same object as x
print(x is y)   # returns False because x is not the same object as y, even if they have the same content
print(x == y)   # to demonstrate the difference betweeen "is" and "==": this comparison returns True because x is equal to y

print(x is not z)  # returns False because z is the same object as x
print(x is not y)   # returns True because x is not the same object as y, even if they have the same content
print(x != y)   # to demonstrate the difference betweeen "is not" and "!=": this comparison returns False because x is equal to y

#Python Membership Operators
x = ["apple", "banana"]
print("banana" in x)      # returns True because a sequence with the value "banana" is in the list
print("pineapple" not in x) # returns True because a sequence with the value "pineapple" is not in the list

8
2
15
1.6666666666666667
2
125
1
5
8
2
6
2.0
2
1
125
1
3
0
0
0
False
True
True
False
True
False
True
True
False
True
False
True
False
True
False
True
True

In [ ]:
#Python Lists
thislist = ["apple", "banana", "cherry"]
print(thislist)

#Lists allow duplicate values:
thislist = ["apple", "banana", "cherry", "apple", "cherry"]
print(thislist)

#List Length
thislist = ["apple", "banana", "cherry"]
print(len(thislist))

#Python methods
#List append() Method
fruits = ['apple', 'banana', 'cherry']
fruits.append("orange")
print(fruits)

a = ["apple", "banana", "cherry"]
b = ["Ford", "BMW", "Volvo"]
a.append(b)
print(a)

#List clear() Method
fruits = ["apple", "banana", "cherry"]
fruits.clear()
print(fruits)

#List copy() Method
fruits = ["apple", "banana", "cherry"]
x = fruits.copy()
print(x)

#List count() Method
fruits = [1, 4, 2, 9, 7, 8, 9, 3, 9]
x = fruits.count(9)
print(x)

#List extend() Method
fruits = ['apple', 'banana', 'cherry']
points = (1, 4, 5, 9)
fruits.extend(points)
print(fruits)

#List index() Method
fruits = [4, 55, 64, 32, 16, 32]
x = fruits.index(64)
print(x)

#List insert() Method
fruits = ['apple', 'banana', 'cherry']
fruits.insert(2, "orange")
print(fruits)

#List pop() Method
fruits = ['apple', 'banana', 'cherry']
x = fruits.pop(2)
print(x)

#List remove() Method
fruits = ['apple', 'banana', 'cherry']
fruits.remove("banana")
print(fruits)

#List reverse() Method
fruits = ['apple', 'banana', 'cherry']
fruits.reverse()
print(fruits)

#List sort() Method
cars = ['Ford', 'BMW', 'Volvo']
cars.sort()
print(cars)

#Access List Items
thislist = ["apple", "banana", "cherry"]
print(thislist[1])
print(thislist[-1]) #negative indexing referes to last item
print(thislist[-2]) #negative indexing referes to second last item

thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5]) # range of indexes, starts with 2 and ends at 5(not included)

#Check if Item Exists
thislist = ["apple", "banana", "cherry"]
if "apple" in thislist:
  print("Yes, 'apple' is in the fruits list")

  #Change List Items
thislist = ["apple", "banana", "cherry"]
thislist[1] = "blackcurrant"
print(thislist)

#Change a Range of Item Values
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)

#Loop Through a List
thislist = ["apple", "banana", "cherry"]
for x in thislist:
  print(x)

#Loop Through the Index Numbers
thislist = ["apple", "banana", "cherry"]
for i in range(len(thislist)):
  print(thislist[i])

#Using a While Loop
thislist = ["apple", "banana", "cherry"]
i = 0
while i < len(thislist):
  print(thislist[i])
  i = i + 1

#Looping Using List Comprehension
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []
for x in fruits:
  if "a" in x:
    newlist.append(x)
print(newlist)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = [x for x in fruits if "m" in x]
print(newlist)

['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry', 'apple', 'cherry']
3
['apple', 'banana', 'cherry', 'orange']
['apple', 'banana', 'cherry', ['Ford', 'BMW', 'Volvo']]
[]
['apple', 'banana', 'cherry']
3
['apple', 'banana', 'cherry', 1, 4, 5, 9]
2
['apple', 'banana', 'orange', 'cherry']
cherry
['apple', 'cherry']
['cherry', 'banana', 'apple']
['BMW', 'Ford', 'Volvo']
banana
cherry
banana
['cherry', 'orange', 'kiwi']
Yes, 'apple' is in the fruits list
['apple', 'blackcurrant', 'cherry']
['apple', 'blackcurrant', 'watermelon', 'orange', 'kiwi', 'mango']
apple
banana
cherry
apple
banana
cherry
apple
banana
cherry
['apple', 'banana', 'mango']
['mango']
<class 'str'>

In [ ]:
#Python Tuples
thistuple = ("apple", "banana", "cherry", "apple", "cherry")
print(thistuple)

#Tuple length
thistuple = ("apple", "banana", "cherry")
print(len(thistuple))

#Tuple with one item
thistuple = ("apple",)
print(type(thistuple))

#Access Tuple Items
thistuple = ("apple", "banana", "cherry")
print(thistuple[1])
print(thistuple[-1])

thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:5])

#Check if Item Exists
thistuple = ("apple", "banana", "cherry")
if "apple" in thistuple:
  print("Yes, 'apple' is in the fruits tuple")

#Change Tuple Values
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)
print(x)

#Add Items
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.append("orange")
thistuple = tuple(y)
print(thistuple)

#Remove Items
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.remove("apple")
thistuple = tuple(y)
print(thistuple)

#Unpacking a tuple:
fruits = ("apple", "banana", "cherry")
(green, yellow, red) = fruits
print(green)
print(yellow)
print(red)

#Loop Through a Tuple
thistuple = ("apple", "banana", "cherry")
for x in thistuple:
  print(x)

#Loop Through the Index Numbers
thistuple = ("apple", "banana", "cherry")
for i in range(len(thistuple)):
  print(thistuple[i])

thistuple = ("apple", "banana", "cherry")
i = 0
while i < len(thistuple):
  print(thistuple[i])
  i = i + 1

#Join Two Tuples
tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)
tuple3 = tuple1 + tuple2
print(tuple3)

#Multiply Tuples
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2
print(mytuple)

('apple', 'banana', 'cherry', 'apple', 'cherry')
3
<class 'tuple'>
banana
cherry
('cherry', 'orange', 'kiwi')
Yes, 'apple' is in the fruits tuple
('apple', 'kiwi', 'cherry')
('apple', 'banana', 'cherry', 'orange')
('banana', 'cherry')
apple
banana
cherry
apple
banana
cherry
apple
banana
cherry
apple
banana
cherry
('a', 'b', 'c', 1, 2, 3)
('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')

In [ ]:
#Python Sets
thisset = {"apple", "banana", "cherry"}
print(thisset)

#duplicate not allowed
thisset = {"apple", "banana", "cherry", "apple"}
print(thisset)

#length of set
thisset = {"apple", "banana", "cherry"}
print(len(thisset))

#Access Set Items
thisset = {"apple", "banana", "cherry"}
for x in thisset:
  print(x)

thisset = {"apple", "banana", "cherry"}
print("banana" in thisset)

#Add Set Items
thisset = {"guava", "banana", "mango"}
thisset.add("orange")
print(thisset)

#Add Sets
thisset = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}
thisset.update(tropical)
print(thisset)

#Remove Set Items
thisset = {"apple", "banana", "cherry"}
thisset.remove("banana")
print(thisset)
thisset.discard("cherry")
print(thisset)
#thisset.remove("mango") #will raise error
thisset.discard("mango") #will not raise error

thisset = {"apple", "banana", "cherry"}
x = thisset.pop() #removes last item
print(x)
print(thisset)

thisset = {"apple", "banana", "cherry"}
thisset.clear() #clears the set
print(thisset)

thisset = {"apple", "banana", "cherry"}
del thisset #delets the set
#print(thisset)  #this will raise an error because the set no longer exists

# Loop items
thisset = {"apple", "banana", "cherry"}
for x in thisset:
  print(x)

#Set methods
#Join two sets
set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}
set3 = set1.union(set2) #exclude duplicates
print(set3)

set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}
set1.update(set2) #exclude duplicate and the join
print(set1)

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
x.intersection_update(y) #keeps only duplicates
print(x)

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
z = x.intersection(y) #return a new set, that only contains the items that are present in both sets
print(z)

#Keep All, But NOT the Duplicates
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
x.symmetric_difference_update(y)
print(x)

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
z = x.symmetric_difference(y)
print(z)

#Set add() Method
fruits = {"apple", "banana", "cherry"}
fruits.add("orange")
print(fruits)

#Set clear() Method
fruits = {"apple", "banana", "cherry"}
fruits.clear()
print(fruits)

#Set copy() Method
fruits = {"apple", "banana", "cherry"}
x = fruits.copy()
print(x)

#Set isdisjoint() Method
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "facebook"}
z = x.isdisjoint(y)
print(z)

#Set issubset() Method
x = {"a", "b", "c"}
y = {"f", "e", "d", "c", "b", "a"}
z = x.issubset(y)
print(z)

#Set issuperset() Method
x = {"f", "e", "d", "c", "b", "a"}
y = {"a", "b", "c"}
z = x.issuperset(y)
print(z)

{'cherry', 'apple', 'banana'}
{'cherry', 'apple', 'banana'}
3
cherry
apple
banana
True
{'guava', 'orange', 'mango', 'banana'}
{'banana', 'pineapple', 'papaya', 'apple', 'mango', 'cherry'}
{'cherry', 'apple'}
{'apple'}
cherry
{'apple', 'banana'}
set()
cherry
apple
banana
{1, 'a', 2, 3, 'c', 'b'}
{1, 'a', 2, 3, 'c', 'b'}
{'apple'}
{'apple'}
{'google', 'microsoft', 'banana', 'cherry'}
{'google', 'microsoft', 'banana', 'cherry'}
{'cherry', 'apple', 'orange', 'banana'}
set()
{'cherry', 'apple', 'banana'}
True
True
True

In [ ]:
#Python Dictionaries
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

#printing single value
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["brand"])

#duplicate not allowed, overriden 
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964,
  "year": 2020
}
print(thisdict)

print(len(thisdict)) #length

#different datatypes
thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}
print(thisdict)

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(type(thisdict))

#Access Dictionary Items
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict["model"]
print (x)
x = thisdict.get("year") #get method
print (x)
x = thisdict.keys()#keys methos
print (x)
x = thisdict.values()#list of all the values
print (x)

#adding new items
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}
x = car.keys()
print(x) #before the change
car["color"] = "white"
print(x) #after the change

car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}
x = car.values()
print(x) #before the change
car["color"] = "red"
print(x) #after the change

#getItems methos
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}
x = car.items()
print(x) #before the change
car["year"] = 2020
print(x) #after the change

#Check if Key Exists
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
if "model" in thisdict:
  print("Yes, 'model' is one of the keys in the thisdict dictionary")

#Change Dictionary Items
#change value
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["year"] = 2018
print(thisdict)

#Update Dictionary
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.update({"year": 2020})
print(thisdict)

#Add Dictionary Items
#Adding Items
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["color"] = "red"
print(thisdict)

#Remove Dictionary Items
#pop() method
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.pop("model")#removes the item with the specified key name
print(thisdict)

#popItem() method
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.popitem()#removes last inserted item
print(thisdict)

#del method()
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
del thisdict["model"]#removes the item with the specified key name
print(thisdict)

#del() deletes entire dictionary 
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
del thisdict
#print(thisdict) #this will cause an error because "thisdict" no longer exists.

#clear() method
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.clear()#empties the dictionary
print(thisdict)

#Loop Dictionaries
#Print all key names in the dictionary, one by one
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for x in thisdict:
  print(x)

#Print all values in the dictionary, one by one
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for x in thisdict:
  print(thisdict[x])

#use the values() method to return values of a dictionary
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for x in thisdict.values():
  print(x)

#use the keys() method to return the keys of a dictionary
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for x in thisdict.keys():
  print(x)

#Loop through both keys and values, by using the items() method
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for x, y in thisdict.items():
  print(x, y)

#Copy Dictionaries
#built-in Dictionary method copy()
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
mydict = thisdict.copy()
print(mydict)

#built-in function dict()
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
mydict = dict(thisdict)
print(mydict)

#Nested Dictionaries
myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}
print(myfamily)

child1 = {
  "name" : "Emil",
  "year" : 2004
}
child2 = {
  "name" : "Tobias",
  "year" : 2007
}
child3 = {
  "name" : "Linus",
  "year" : 2011
}
myfamily = {
  "child1" : child1,
  "child2" : child2,
  "child3" : child3
}
print(myfamily)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Ford
{'brand': 'Ford', 'model': 'Mustang', 'year': 2020}
3
{'brand': 'Ford', 'electric': False, 'year': 1964, 'colors': ['red', 'white', 'blue']}
<class 'dict'>
Mustang
1964
dict_keys(['brand', 'model', 'year'])
dict_values(['Ford', 'Mustang', 1964])
dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'color'])
dict_values(['Ford', 'Mustang', 1964])
dict_values(['Ford', 'Mustang', 1964, 'red'])
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 2020)])
Yes, 'model' is one of the keys in the thisdict dictionary
{'brand': 'Ford', 'model': 'Mustang', 'year': 2018}
{'brand': 'Ford', 'model': 'Mustang', 'year': 2020}
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}
{'brand': 'Ford', 'year': 1964}
{'brand': 'Ford', 'model': 'Mustang'}
{'brand': 'Ford', 'year': 1964}
{}
brand
model
year
Ford
Mustang
1964
Ford
Mustang
1964
brand
model
year
brand Ford
model Mustang
year 1964
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
{'child1': {'name': 'Emil', 'year': 2004}, 'child2': {'name': 'Tobias', 'year': 2007}, 'child3': {'name': 'Linus', 'year': 2011}}
{'child1': {'name': 'Emil', 'year': 2004}, 'child2': {'name': 'Tobias', 'year': 2007}, 'child3': {'name': 'Linus', 'year': 2011}}

In [ ]:
#Python Conditions and If statements
#if statement
a = 33
b = 200
if b > a:
  print("b is greater than a")

#Elif
a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

#Else
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

a = 200
b = 33
if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")

#Short Hand If
a = 200
b = 33
if a > b: print("a is greater than b")

#Short Hand If ... Else
a = 2
b = 330
print("A") if a > b else print("B")

a = 330
b = 330
print("A") if a > b else print("=") if a == b else print("B")

#And
a = 200
b = 33
c = 500
if a > b and c > a:
  print("Both conditions are True")

#Or
a = 200
b = 33
c = 500
if a > b or a > c:
  print("At least one of the conditions is True")

#Nested If
x = 41
if x > 10:
  print("Above ten,")
  if x > 20:
    print("and also above 20!")
  else:
    print("but not above 20.")

#The pass Statement
a = 33
b = 200
if b > a:
  pass #if statements cannot be empty, but if you for some reason have an if statement with no content, put in the pass statement to avoid getting an error

b is greater than a
a and b are equal
a is greater than b
b is not greater than a
a is greater than b
B
=
Both conditions are True
At least one of the conditions is True
Above ten,
and also above 20!

In [ ]:
#Python While Loops
i = 1
while i < 6:
  print(i)
  i += 1

#The break Statement, stop the loop even if the while condition is true
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1
#The continue Statement, can stop the current iteration, and continue with the next
i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

1
2
3
4
5
1
2
3
1
2
4
5
6

In [ ]:
#Python For Loops
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

#Looping Through a String
for x in "banana":
  print(x)

#The range() Function
for x in range(5):
  print(x)

for x in range(2,6):
  print(x)

for x in range(2, 30, 3):
  print(x)

#Else in For Loop
for x in range(6):
  print(x)
else:
  print("Finally finished!")

#Nested Loops
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]
for x in adj:
  for y in fruits:
    print(x, y)

apple
banana
cherry
b
a
n
a
n
a
0
1
2
3
4
2
3
4
5
2
5
8
11
14
17
20
23
26
29
0
1
2
3
4
5
Finally finished!
red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry

In [ ]:
#Python Functions
#Creating & calling a Function
def my_function():
  print("Hello from a function")
my_function()

#Arguments
def my_function(fname):
  print(fname + " Refsnes")
my_function("Emil")
my_function("Tobias")
my_function("Linus")

#2 arguments
def my_function(fname, lname):
  print(fname + " " + lname)
my_function("Emil", "Refsnes")

#Arbitrary Arguments, *args
def my_function(*kids):
  print("The youngest child is " + kids[3])
my_function("Emil", "Tobias", "Linus", "Batul")

def my_function(child3, child2, child1):
  print("The youngest child is " + child3)
my_function(child1 = "Emil", child2 = "Tobias", child3 = "Linus")

#Arbitrary Keyword Arguments, **kwargs
def my_function(**kid):
  print("His last name is " + kid["lname"])
my_function(fname = "Tobias", lname = "Refsnes")

#Default Parameter Value
def my_function(country = "Norway"):
  print("I am from " + country)
my_function("Sweden")
my_function("India")
my_function()
my_function("Brazil")

#Passing a List as an Argument
def my_function(food):
  for x in food:
    print(x)
fruits = ["apple", "banana", "cherry"]
my_function(fruits)

#Return Values
def my_function(x):
  return 5 * x
print(my_function(3))
print(my_function(5))
print(my_function(9))

Hello from a function
Emil Refsnes
Tobias Refsnes
Linus Refsnes
Emil Refsnes
The youngest child is Batul
The youngest child is Linus
His last name is Refsnes
I am from Sweden
I am from India
I am from Norway
I am from Brazil
apple
banana
cherry
15
25
45

In [ ]:
#Python Lambda
x = lambda a : a + 10
print(x(5))

x = lambda a : a + 10
print(x(4))

x = lambda a, b, c : a + b + c
print(x(5, 6, 2))

def myfunc(n):
  return lambda a : a * n
mydoubler = myfunc(2)
print(mydoubler(11))

def myfunc(n):
  return lambda a : a * n
mydoubler = myfunc(2)
mytripler = myfunc(3)
print(mydoubler(11))
print(mytripler(11))

15
14
13
22
22
33

In [8]:
#Python arrays
cars = ["Ford", "Volvo", "BMW"]
print(cars)

#accessing array elements
cars = ["Ford", "Volvo", "BMW"]
x = cars[0]
print(x)

#modify value of arary elements
cars = ["Ford", "Volvo", "BMW"]
cars[1] = "Toyota"
print(cars)

#l3ngth of array
cars = ["Ford", "Volvo", "BMW"]
x = len(cars)
print(x)

#looping array elements
cars = ["Ford", "Volvo", "BMW"]
for x in cars:
  print(x)

#adding array elements
cars = ["Ford", "Volvo", "BMW"]
cars.append("Honda")
print(cars)

#removing array elements
cars = ["Ford", "Volvo", "BMW"]
cars.pop(1)
print(cars)
cars.remove("Ford")
print(cars)

['Ford', 'Volvo', 'BMW']
Ford
['Ford', 'Toyota', 'BMW']
3
Ford
Volvo
BMW
['Ford', 'Volvo', 'BMW', 'Honda']
['Ford', 'BMW']
['BMW']

In [19]:
#Python Classes and Objects
#Create a Class
class MyClass:
  x = 5
print(MyClass)

#Create Object
class MyClass:
  x = 5
p1 = MyClass()
print(p1.x)

#The __init__() Function
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
p1 = Person("John", 36)
print(p1.name)
print(p1.age)

#The __init__() Function
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
p1 = Person("John", 36)
print(p1)

#The __str__() Function
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def __str__(self):
    return f"{self.name}({self.age})"
p1 = Person("John", 36)
print(p1)

#Object Methods
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def myfunc(self):
    print("Hello my name is " + self.name)
p1 = Person("John", 36)
p1.myfunc()

#The self Parameter
class Person:
  def __init__(mysillyobject, name, age):
    mysillyobject.name = name
    mysillyobject.age = age
  def myfunc(abc):
    print("Hello my name is " + abc.name)
p1 = Person("John", 36)
p1.myfunc()

#Modify Object Properties
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def myfunc(self):
    print("Hello my name is " + self.name)
p1 = Person("John", 36)
p1.age = 40
print(p1.age)

#Delete Object Properties
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def myfunc(self):
    print("Hello my name is " + self.name)
p1 = Person("John", 36)
del p1.age
#print(p1.age)

<class '__main__.MyClass'>
5
John
36
<__main__.Person object at 0x7f65e16be210>
John(36)
Hello my name is John
Hello my name is John
40

AttributeError: ignored